version: 2.1

setup: true

orbs:
  codecov: codecov/codecov@1.2.3

jobs:
  build:
    docker:
      - image: circleci/node:16
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-16-{{ checksum "package.json" }}
            - v1-dependencies-16-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-16-{{ checksum "package.json" }}
      - run: CI=false yarn build
  test:
    docker:
      - image: circleci/node:16
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-16-{{ checksum "package.json" }}
            - v1-dependencies-16-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-16-{{ checksum "package.json" }}
      - run: CI=false yarn lint
      - run: yarn test-ci
      - store_test_results:
          path: ./test-results
      - codecov/upload:
          file: "./coverage/lcov.info"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
