on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Publish to Chromatic
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --allow-console-errors --exit-zero-on-changes --auto-accept-changes main
